#!/bin/bash

declare -a dirs=(
"/git"
)
for dir in ${dirs[@]}; do
    for repo in `ls -d ${dir}/*`; do
        cd "$repo"
        pwd
        git pull &> /dev/null || (notify-send -u critical "Git pull conflict" "$repo" && continue)
        git status | grep "nothing to commit" &>/dev/null || notify-send -t 6000 "Uncommited changes" "$repo"
    done
done
